import React from 'react';
import { DollarSign, Layers, EyeOff, TrendingDown, Database, CheckCircle2, Cpu, GitCommit } from 'lucide-react';

interface MetricTickerProps {
  perspective: 'commercial' | 'technical';
}

export const MetricTicker: React.FC<MetricTickerProps> = ({ perspective }) => {
  const commercialMetrics = [
    {
      icon: <DollarSign size={22} color="#f59e0b" />,
      value: '$118,500+',
      label: 'Annual Revenue Preserved',
      sub: 'Algorithmic Churn Thresholding',
      accent: '#f59e0b'
    },
    {
      icon: <Layers size={22} color="#f59e0b" />,
      value: '88%',
      label: 'Whale Revenue Share',
      sub: 'Generated by Top 40% Spenders',
      accent: '#f59e0b'
    },
    {
      icon: <EyeOff size={22} color="#14b8a6" />,
      value: '-31.0pp',
      label: 'Mobile Conversion Drop',
      sub: 'Checkout Drop-off Identified',
      accent: '#14b8a6'
    },
    {
      icon: <TrendingDown size={22} color="#f59e0b" />,
      value: '+22.3%',
      label: 'Planning Error Reduced',
      sub: 'Preventing Inventory Stockouts',
      accent: '#f59e0b'
    },
    {
      icon: <DollarSign size={22} color="#14b8a6" />,
      value: '65%',
      label: 'Lost GMV Concentrated',
      sub: 'Inside High-Value Abandoned Carts',
      accent: '#14b8a6'
    },
    {
      icon: <TrendingDown size={22} color="#f59e0b" />,
      value: '₹6.2M',
      label: 'Revenue Slide Diagnosed',
      sub: 'Volume Drop vs AOV Decoupled',
      accent: '#f59e0b'
    }
  ];

  const technicalMetrics = [
    {
      icon: <Database size={22} color="#14b8a6" />,
      value: '1.15M+',
      label: 'Records Orchestrated',
      sub: 'Airflow 3 · Dual Ingestion CDC',
      accent: '#14b8a6'
    },
    {
      icon: <CheckCircle2 size={22} color="#10b981" />,
      value: '103',
      label: 'dbt Schema Contracts',
      sub: '100% Passing CI/CD Verification',
      accent: '#10b981'
    },
    {
      icon: <TrendingDown size={22} color="#f59e0b" />,
      value: '19.20%',
      label: 'Huber Model WMAPE',
      sub: 'Expanding TimeSeriesSplit CV',
      accent: '#f59e0b'
    },
    {
      icon: <EyeOff size={22} color="#14b8a6" />,
      value: 'p = 0.015',
      label: 'Two-Proportion Z-Test',
      sub: 'Wald 95% Confidence Intervals',
      accent: '#14b8a6'
    },
    {
      icon: <Cpu size={22} color="#14b8a6" />,
      value: 'SCD Type II',
      label: 'Historical State Tracking',
      sub: 'Zero Data Loss on Plan Mutations',
      accent: '#14b8a6'
    },
    {
      icon: <GitCommit size={22} color="#f59e0b" />,
      value: '48 Features',
      label: 'Leak-Free Engineered Lags',
      sub: 'Strict Cutoff Boundary Audits',
      accent: '#f59e0b'
    }
  ];

  const metrics = perspective === 'commercial' ? commercialMetrics : technicalMetrics;

  return (
    <section className="metrics-section">
      <div className="container">
        <div className="metrics-grid">
          {metrics.map((m, idx) => (
            <div
              key={idx}
              className="metric-card"
              style={{ '--card-accent': m.accent } as React.CSSProperties}
            >
              <div style={{ marginBottom: '10px' }}>{m.icon}</div>
              <div className="metric-value">{m.value}</div>
              <div className="metric-label">{m.label}</div>
              <div className="metric-sub">{m.sub}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
